// Coffee Database - Shared across the app
export const coffeeDatabase = [
    {
        id: "ethiopian-yirgacheffe",
        name: "Ethiopian Yirgacheffe",
        origin: "Ethiopia",
        roastLevel: "light",
        flavors: ["fruity", "floral", "citrus"],
        acidity: "high",
        body: "light",
        description: "A bright, complex coffee with distinctive floral and citrus notes. Known for its wine-like acidity and tea-like body.",
        detailedDescription: "Ethiopian Yirgacheffe is a world-renowned coffee celebrated for its unique and delicate flavor profile. Grown at high elevations in southern Ethiopia, the beans develop a bright, clean taste with prominent floral notes like jasmine and citrus hints of lemon and bergamot. Its light body and wine-like acidity make it a favorite for pour-over brewing methods, which highlight its nuanced flavors. This coffee offers a truly aromatic and refreshing experience.",
        rating: 4.8,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuATb2XZqaCzBdZYzddT0Wn9qvJzyScjrmamX4AhUbtnPpd3lq9pYhxEtBwwdC98QAKC3SvGErncbYN8ukk16ilwv3YSlTxC5QO2zi4W4W2u8NXAwIZP7vjHnBBvShYo-zffLpHPfsmWiEXf1F6Odp6bArjW5UZZJWgqql4v_e3MlCJKqdxAz30pFsI3KsaEceh1yIjeY8EoF9TJuGx_BrU_aSaXkfQjuQRzfK6B-i4YVSpiAZdjSW9BKe0I5Wx9NzYaSGbTKyYuGaM"
    },
    {
        id: "colombian-supremo",
        name: "Colombian Supremo",
        origin: "Colombia",
        roastLevel: "medium",
        flavors: ["chocolate", "nutty", "caramel"],
        acidity: "medium",
        body: "medium",
        description: "A well-balanced coffee with smooth chocolate notes, subtle nuttiness, and a hint of caramel sweetness.",
        detailedDescription: "Colombian Supremo is the quintessential balanced coffee. It boasts a medium body and acidity, making it incredibly smooth and approachable. The flavor profile is characterized by rich notes of milk chocolate, toasted nuts like almond, and a sweet caramel finish. These beans are versatile and perform exceptionally well in various brewing methods, from drip to espresso, delivering a consistently satisfying cup.",
        rating: 4.6,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB-MGGI9tENcxedPjSbrZwfxS4hnODLieEn42JJxV9dcVZry1HAFvZpl6Z-bn9bAFIp9I2mNDw1trpf3gJfZzUl_ICZSXeN4ghKCHJ8Q1kMc-NZ7xz98UXHrcooNfKlJtHgPv7A68kVaHbmnsu1NmzK0Xa2ePnMfPHeF-WiYSEd8BafBuRUIh23ZcBM4UAPA8WDSclOSoSLP8PE4AxGk7_dw8WKdKpO-UmFfIy-S0W989YP0a8Row8y8cM1MN_62EY4mlF_E3LTnxA"
    },
    {
        id: "brazilian-santos",
        name: "Brazilian Santos",
        origin: "Brazil",
        roastLevel: "medium-dark",
        flavors: ["nutty", "chocolate", "earthy"],
        acidity: "low",
        body: "full",
        description: "A smooth, low-acid coffee with rich nutty flavors and a full body. Perfect for those who prefer milder acidity.",
        detailedDescription: "Brazilian Santos is a classic coffee known for its smooth, mellow character and low acidity. It features a full body with dominant flavors of roasted nuts and rich cocoa. A subtle earthy undertone adds complexity, making it a comforting and satisfying brew. It's an excellent choice for espresso blends or for those who enjoy a less acidic, full-flavored coffee experience.",
        rating: 4.4,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwMn5B2Iqf65mRknqg9JXtn5Nb-dDP5nqQOsPuJSlnTdBNUijzVJb8gVLNR1TXnnuoFiTN-kW22VGK88W9onRAjm5vtYvt7ukK6-7UDgrGVArCCcrMZSHOK4uFaa-jx129e1vk2d6P0FUmNBsNmvxkuZUH3azLKHweP1eLmx0QkSzEy1rw2LzxTQ3IAZCJrAHUYFEMCF5JoIixeOtNOp8ZAkPn8ZlvFlZLKz8RuOC6r2uTyJ_bDKal7d4_6cVDX4uJihIUa3gQMow"
    },
    {
        id: "guatemalan-antigua",
        name: "Guatemalan Antigua",
        origin: "Guatemala",
        roastLevel: "medium",
        flavors: ["chocolate", "spicy", "earthy"],
        acidity: "medium",
        body: "full",
        description: "A full-bodied coffee with rich chocolate notes, subtle spice, and a smooth finish with medium acidity.",
        detailedDescription: "Grown in the volcanic highlands of Antigua, this coffee is known for its complexity and depth. It has a full body and a bright, yet balanced, acidity. The flavor profile is dominated by dark chocolate notes, complemented by hints of warm spices like cinnamon and clove, and a pleasant, lingering finish. It's a sophisticated coffee that is both rich and vibrant.",
        rating: 4.7,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuATb2XZqaCzBdZYzddT0Wn9qvJzyScjrmamX4AhUbtnPpd3lq9pYhxEtBwwdC98QAKC3SvGErncbYN8ukk16ilwv3YSlTxC5QO2zi4W4W2u8NXAwIZP7vjHnBBvShYo-zffLpHPfsmWiEXf1F6Odp6bArjW5UZZJWgqql4v_e3MlCJKqdxAz30pFsI3KsaEceh1yIjeY8EoF9TJuGx_BrU_aSaXkfQjuQRzfK6B-i4YVSpiAZdjSW9BKe0I5Wx9NzYaSGbTKyYuGaM"
    },
    {
        id: "costa-rican-tarrazu",
        name: "Costa Rican Tarrazu",
        origin: "Costa Rica",
        roastLevel: "medium",
        flavors: ["fruity", "chocolate", "citrus"],
        acidity: "high",
        body: "medium",
        description: "A bright, clean coffee with vibrant fruit notes, balanced chocolate undertones, and crisp citrus acidity.",
        detailedDescription: "From the Tarrazú region of Costa Rica, this coffee is known for its sharp, bright acidity and clean finish. It presents a lively flavor profile with notes of apricot and citrus, perfectly balanced by a sweet, milk chocolate base. Its medium body and crispness make it an exceptionally refreshing and well-structured coffee, often regarded as one of the world's best.",
        rating: 4.5,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB-MGGI9tENcxedPjSbrZwfxS4hnODLieEn42JJxV9dcVZry1HAFvZpl6Z-bn9bAFIp9I2mNDw1trpf3gJfZzUl_ICZSXeN4ghKCHJ8Q1kMc-NZ7xz98UXHrcooNfKlJtHgPv7A68kVaHbmnsu1NmzK0Xa2ePnMfPHeF-WiYSEd8BafBuRUIh23ZcBM4UAPA8WDSclOSoSLP8PE4AxGk7_dw8WKdKpO-UmFfIy-S0W989YP0a8Row8y8cM1MN_62EY4mlF_E3LTnxA"
    },
    {
        id: "kenyan-aa",
        name: "Kenyan AA",
        origin: "Kenya",
        roastLevel: "medium",
        flavors: ["fruity", "citrus", "spicy"],
        acidity: "high",
        body: "medium",
        description: "A bold, bright coffee with intense berry flavors, zesty citrus notes, and a distinctive spicy finish.",
        detailedDescription: "Kenyan AA is one of the world's most prized coffees, known for its incredible complexity and powerful character. It features a bold, wine-like acidity with intense flavors of blackcurrant and blackberry, complemented by zesty grapefruit notes. A savory, spicy finish adds another layer of depth. It's a truly remarkable and memorable coffee experience.",
        rating: 4.8,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwMn5B2Iqf65mRknqg9JXtn5Nb-dDP5nqQOsPuJSlnTdBNUijzVJb8gVLNR1TXnnuoFiTN-kW22VGK88W9onRAjm5vtYvt7ukK6-7UDgrGVArCCcrMZSHOK4uFaa-jx129e1vk2d6P0FUmNBsNmvxkuZUH3azLKHweP1eLmx0QkSzEy1rw2LzxTQ3IAZCJrAHUYFEMCF5JoIixeOtNOp8ZAkPn8ZlvFlZLKz8RuOC6r2uTyJ_bDKal7d4_6cVDX4uJihIUa3gQMow"
    },
    {
        id: "sumatra-mandheling",
        name: "Sumatra Mandheling",
        origin: "Sumatra",
        roastLevel: "dark",
        flavors: ["earthy", "spicy", "chocolate"],
        acidity: "low",
        body: "full",
        description: "A full-bodied, low-acid coffee with deep earthy notes, rich chocolate undertones, and a spicy complexity.",
        detailedDescription: "Sumatra Mandheling is famous for its heavy, syrupy body and very low acidity. Its flavor profile is distinctively earthy and complex, with notes of dark chocolate, cedar, and sweet tobacco. A hint of spice often lingers in the finish. This is a bold and intense coffee, perfect for those who appreciate a rich and unconventional cup.",
        rating: 4.3,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuATb2XZqaCzBdZYzddT0Wn9qvJzyScjrmamX4AhUbtnPpd3lq9pYhxEtBwwdC98QAKC3SvGErncbYN8ukk16ilwv3YSlTxC5QO2zi4W4W2u8NXAwIZP7vjHnBBvShYo-zffLpHPfsmWiEXf1F6Odp6bArjW5UZZJWgqql4v_e3MlCJKqdxAz30pFsI3KsaEceh1yIjeY8EoF9TJuGx_BrU_aSaXkfQjuQRzfK6B-i4YVSpiAZdjSW9BKe0I5Wx9NzYaSGbTKyYuGaM"
    },
    {
        id: "jamaican-blue-mountain",
        name: "Jamaican Blue Mountain",
        origin: "Jamaica",
        roastLevel: "medium",
        flavors: ["chocolate", "nutty", "floral"],
        acidity: "medium",
        body: "medium",
        description: "A smooth, mild coffee with balanced chocolate and nutty flavors, subtle floral notes, and a clean finish.",
        detailedDescription: "Jamaican Blue Mountain is one of the most famous and sought-after coffees in the world. It is exceptionally smooth and well-balanced, with a mild flavor and a clean finish, completely lacking any bitterness. It features subtle notes of milk chocolate, toasted nuts, and a delicate floral aroma. Its legendary mildness makes it a luxurious and highly prized coffee.",
        rating: 4.9,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB-MGGI9tENcxedPjSbrZwfxS4hnODLieEn42JJxV9dcVZry1HAFvZpl6Z-bn9bAFIp9I2mNDw1trpf3gJfZzUl_ICZSXeN4ghKCHJ8Q1kMc-NZ7xz98UXHrcooNfKlJtHgPv7A68kVaHbmnsu1NmzK0Xa2ePnMfPHeF-WiYSEd8BafBuRUIh23ZcBM4UAPA8WDSclOSoSLP8PE4AxGk7_dw8WKdKpO-UmFfIy-S0W989YP0a8Row8y8cM1MN_62EY4mlF_E3LTnxA"
    },
    {
        id: "peruvian-organic",
        name: "Peruvian Organic",
        origin: "Peru",
        roastLevel: "medium",
        flavors: ["nutty", "chocolate", "caramel"],
        acidity: "medium",
        body: "medium",
        description: "A well-rounded organic coffee with smooth nutty flavors, rich chocolate notes, and a hint of caramel sweetness.",
        detailedDescription: "Peruvian organic coffee is known for its smooth and mellow character. It has a medium body and a mild, pleasant acidity. The flavor profile is gentle and well-rounded, with notes of toasted almond, milk chocolate, and a soft caramel sweetness. It's an easy-drinking coffee that is both comforting and satisfying, grown using sustainable organic practices.",
        rating: 4.4,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwMn5B2Iqf65mRknqg9JXtn5Nb-dDP5nqQOsPuJSlnTdBNUijzVJb8gVLNR1TXnnuoFiTN-kW22VGK88W9onRAjm5vtYvt7ukK6-7UDgrGVArCCcrMZSHOK4uFaa-jx129e1vk2d6P0FUmNBsNmvxkuZUH3azLKHweP1eLmx0QkSzEy1rw2LzxTQ3IAZCJrAHUYFEMCF5JoIixeOtNOp8ZAkPn8ZlvFlZLKz8RuOC6r2uTyJ_bDKal7d4_6cVDX4uJihIUa3gQMow"
    },
    {
        id: "honduran-marcala",
        name: "Honduran Marcala",
        origin: "Honduras",
        roastLevel: "medium-dark",
        flavors: ["chocolate", "caramel", "nutty"],
        acidity: "low",
        body: "full",
        description: "A full-bodied coffee with rich chocolate and caramel notes, smooth nuttiness, and a low-acid profile.",
        detailedDescription: "From the Marcala region of Honduras, this coffee is prized for its rich and creamy profile. It has a full body and low acidity, making it incredibly smooth. The flavor is dominated by deep notes of dark chocolate and buttery caramel, with a pleasant nutty finish. It is often described as a 'dessert coffee' due to its rich and decadent character.",
        rating: 4.2,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuATb2XZqaCzBdZYzddT0Wn9qvJzyScjrmamX4AhUbtnPpd3lq9pYhxEtBwwdC98QAKC3SvGErncbYN8ukk16ilwv3YSlTxC5QO2zi4W4W2u8NXAwIZP7vjHnBBvShYo-zffLpHPfsmWiEXf1F6Odp6bArjW5UZZJWgqql4v_e3MlCJKqdxAz30pFsI3KsaEceh1yIjeY8EoF9TJuGx_BrU_aSaXkfQjuQRzfK6B-i4YVSpiAZdjSW9BKe0I5Wx9NzYaSGbTKyYuGaM"
    },
    {
        id: "nicaraguan-jinotega",
        name: "Nicaraguan Jinotega",
        origin: "Nicaragua",
        roastLevel: "medium",
        flavors: ["chocolate", "fruity", "caramel"],
        acidity: "medium",
        body: "medium",
        description: "A balanced coffee with smooth chocolate notes, subtle fruit undertones, and a hint of caramel sweetness.",
        detailedDescription: "Nicaraguan coffee from the Jinotega region is known for its well-balanced and complex profile. It has a medium body and a bright but smooth acidity. The flavor profile is diverse, featuring notes of milk chocolate, sweet caramel, and a hint of fruitiness, often reminiscent of apple or pear. It's a versatile and satisfying coffee that showcases the best of Central American beans.",
        rating: 4.3,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB-MGGI9tENcxedPjSbrZwfxS4hnODLieEn42JJxV9dcVZry1HAFvZpl6Z-bn9bAFIp9I2mNDw1trpf3gJfZzUl_ICZSXeN4ghKCHJ8Q1kMc-NZ7xz98UXHrcooNfKlJtHgPv7A68kVaHbmnsu1NmzK0Xa2ePnMfPHeF-WiYSEd8BafBuRUIh23ZcBM4UAPA8WDSclOSoSLP8PE4AxGk7_dw8WKdKpO-UmFfIy-S0W989YP0a8Row8y8cM1MN_62EY4mlF_E3LTnxA"
    },
    {
        id: "mexican-chiapas",
        name: "Mexican Chiapas",
        origin: "Mexico",
        roastLevel: "medium-dark",
        flavors: ["chocolate", "nutty", "earthy"],
        acidity: "low",
        body: "full",
        description: "A full-bodied coffee with rich chocolate notes, smooth nuttiness, and earthy undertones with low acidity.",
        detailedDescription: "Grown in the highlands of Chiapas, Mexico, this coffee is known for its large beans and rich flavor. It has a full body and low acidity, with a profile dominated by deep chocolate and nutty flavors. A pleasant earthy undertone adds complexity, resulting in a well-rounded and satisfying cup. It's a great choice for those who enjoy a rich but smooth coffee experience.",
        rating: 4.1,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwMn5B2Iqf65mRknqg9JXtn5Nb-dDP5nqQOsPuJSlnTdBNUijzVJb8gVLNR1TXnnuoFiTN-kW22VGK88W9onRAjm5vtYvt7ukK6-7UDgrGVArCCcrMZSHOK4uFaa-jx129e1vk2d6P0FUmNBsNmvxkuZUH3azLKHweP1eLmx0QkSzEy1rw2LzxTQ3IAZCJrAHUYFEMCF5JoIixeOtNOp8ZAkPn8ZlvFlZLKz8RuOC6r2uTyJ_bDKal7d4_6cVDX4uJihIUa3gQMow"
    }
]; 